# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, happstackServer }:

cabal.mkDerivation (self: {
  pname = "tinklive";
  version = "0.1.0.0";
  src = ./.;
  isLibrary = false;
  isExecutable = true;
  buildDepends = [ happstackServer ];
  meta = {
    homepage = "www.tinkhaven.com";
    description = "Live environment for Tinkhaven";
    license = self.stdenv.lib.licenses.mit;
    platforms = self.ghc.meta.platforms;
  };
})
